// Example notebooks, shown in the gallery and used as templates. Every one is opened and run by
// the test suite (tests/workspace.test.mjs), so none of them may produce an error.
const nb = (title, desc, tags, cells) => ({ title, desc, tags, cells: cells.map(c => typeof c === 'string' ? { type: 'text', content: c } : { type: 'math', mode: c[0], expr: c[1] }) });

export const GALLERY = [
  nb('Calculus I', 'Limits, derivatives with worked steps, integrals, the fundamental theorem.', ['calculus', 'template'], [
    '# Calculus I\nPress ∴ Steps on any result to see how it was done.',
    ['calculus', 'lim x->0 sin(x)/x'],
    ['calculus', 'd/dx x^2 sin(x)'],
    ['calculus', 'integral of x e^x dx'],
    ['calculus', 'f(x) = x^3 - 3x'],
    ['calculus', 'extrema(f(x), x)'],
    ['calculus', 'integrate(f(x), x, 0, 2)'],
    ['calculus', 'plot(f(x), [x, -2.5, 2.5])'],
  ]),
  nb('Linear algebra', 'Determinants, eigenvalues, diagonalisation, least squares.', ['matrices', 'template'], [
    '# Linear algebra',
    ['matrix', 'A = [[2, 1], [1, 2]]'],
    ['matrix', 'det(A)'],
    ['matrix', 'eigs(A)'],
    ['matrix', 'diagonalize(A)'],
    ['matrix', 'rref([[1, 2, 3], [4, 5, 6], [7, 8, 10]])'],
    ['matrix', 'lll([[1, 1, 1], [-1, 0, 2], [3, 5, 6]])'],
  ]),
  nb('Differential equations', 'Solving ODEs exactly, slope fields, a system eliminated to one equation.', ['ode', 'template'], [
    '# Differential equations',
    ['calculus', "y'' + y = 0, y(0) = 0, y'(0) = 1"],
    ['calculus', "y' = x*y"],
    ['calculus', 'plot(slopefield(x - y), [x, -4, 4])'],
    ['calculus', "diffelim([x' = y, y' = -x], [x], t)"],
    ['calculus', 'laplace(t^2*exp(-t), t, s)'],
  ]),
  nb('Probability', 'Random variables as objects: probabilities, expectations, densities.', ['statistics', 'template'], [
    '# Probability\nDefine a random variable once and use it everywhere.',
    ['stats', 'X ~ Normal(100, 15)'],
    ['stats', 'P(X > 130)'],
    ['stats', 'E(X^2)'],
    ['stats', 'Y = Binomial(20, 0.3)'],
    ['stats', 'P(Y = 6)'],
    ['stats', 'histogram([2, 3, 3, 4, 4, 4, 5, 5, 6, 9])'],
  ]),
  nb('Geometry constructions', 'Points, triangles and circles that update when you move a point.', ['geometry'], [
    '# Geometry\nEdit B and everything built from it is recomputed.',
    ['algebra', 'A = Point(0, 0)'],
    ['algebra', 'B = Point(6, 0)'],
    ['algebra', 'C = Point(2, 4)'],
    ['algebra', 'T = Triangle(A, B, C)'],
    ['algebra', 'area(T)'],
    ['algebra', 'circumcircle(T)'],
    ['algebra', 'incircle(T)'],
  ]),
  nb('Number theory', 'Primes, factorisation, modular arithmetic, continued fractions.', ['numtheory'], [
    '# Number theory',
    ['numtheory', 'factorint(2^32 + 1)'],
    ['numtheory', 'isprime(2^61 - 1)'],
    ['numtheory', 'powmod(2, 10^18, 10^9 + 7)'],
    ['numtheory', 'crt([2, 3, 2], [3, 5, 7])'],
    ['numtheory', 'contfrac(sqrt(7))'],
    ['numtheory', 'galois(x^5 - x - 1)'],
  ]),
  nb('Signals and systems', 'Laplace and Z-transforms, convolution, a Bode plot.', ['signals'], [
    '# Signals and systems',
    ['calculus', 'convolve(exp(-t), exp(-2t), t)'],
    ['calculus', 'ztrans(2^n, n, z)'],
    ['calculus', 'iztrans(z/(z^2 + 1), z, n)'],
    ['calculus', 'dft([1, 2, 3, 4])'],
    ['calculus', 'bode(1/(s + 1), s)'],
  ]),
  nb('Curvature and relativity', 'Christoffel symbols, the curvature of a sphere, Schwarzschild is a vacuum.', ['geometry', 'physics'], [
    '# Curvature',
    ['calculus', 'christoffel([[1, 0], [0, r^2]], [r, theta])'],
    ['calculus', 'ricciscalar([[r^2, 0], [0, r^2 sin(theta)^2]], [theta, phi])'],
    ['calculus', 'surfcurv([sin(u) cos(v), sin(u) sin(v), cos(u)], [u, v])'],
    ['calculus', 'einstein([[-(1 - 2M/r), 0, 0, 0], [0, 1/(1 - 2M/r), 0, 0], [0, 0, r^2, 0], [0, 0, 0, r^2 sin(theta)^2]], [t, r, theta, phi])'],
  ]),
  nb('Proofs and certainty', 'Identities proved by canonical forms, inequalities by Sturm sequences and interval arithmetic.', ['proofs'], [
    '# Proofs\nA proof, a counterexample, or an honest "not proved".',
    ['algebra', 'prove(sin(x)^2 + cos(x)^2 = 1)'],
    ['algebra', 'prove((x + y)^2 = x^2 + y^2)'],
    ['algebra', 'prove(x^4 - 4x^3 + 6x^2 - 4x + 1 >= 0)'],
    ['algebra', 'prove(exp(x) >= 1 + x, [x, -2, 2])'],
    ['numeric', 'ieval(sin(x) + atan(x), [x, 0, 1])'],
  ]),
  nb('Quantum and knots', 'A Bell state, a GHZ state, and knot invariants.', ['physics', 'topology'], [
    '# Quantum circuits and knots',
    ['algebra', 'circuit(2, H(0), CNOT(0, 1))'],
    ['algebra', 'circuit(3, H(0), CNOT(0, 1), CNOT(1, 2))'],
    ['algebra', 'alexander(figure8)'],
    ['algebra', 'jones(trefoil)'],
  ]),
  nb('Visual mathematics', 'Riemann surfaces, implicit surfaces, domain colouring, networks.', ['plots'], [
    '# Pictures',
    ['calculus', 'riemann(sqrt(z))'],
    ['calculus', 'plot3d(x^2 + y^2 - z^2 = 1)'],
    ['algebra', 'domaincolor((z^2 - 1)/(z^2 + 1))'],
    ['algebra', 'graph([[0, 1, 1, 0], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 0]])'],
    ['algebra', 'tree(x^2 + 3*sin(x)/2)'],
  ]),
  nb('Blank', 'An empty notebook.', ['template'], []),
];
